repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: [ '--unsafe' ]
        types: [file,  yaml]
        exclude: helm/
  - repo: local
    hooks:
      - id: maven-spotless
        name: maven-spotless
        entry: mvn spotless:check
        language: system
        types: [java]
        pass_filenames: false
