receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:6666

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]