global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: otel_collector
    static_configs:
      - targets: [ "collector:6666" ]
#  - job_name: prometheus
#    static_configs:
#      - targets: [ "localhost:9090" ]
#  - job_name: tempo
#    static_configs:
#      - targets: [ "tempo:3200" ]