apiVersion: v2
name: dq-sifflet-tech-adapter
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
maintainers:
  - name: AgileLab
    url: http://agilelab.it